apiVersion: apps/v1
kind: Deployment
metadata:
  name: nsot
spec:
  selector:
    matchLabels:
      app: nsot
  replicas: 1
  template:
    metadata:
      labels:
        app: nsot
    spec:
      containers:
      - name: nsot
        image: "docker.io/nsot/nsot:latest"
