---
apiVersion: v1
kind: Service
metadata:
  name: nsot
  namespace: service
spec:
  selector:
    matchLabels:
      app: nsot
  ports:
  - name: nsot
    protocol: TCP
    port: 8990
    targetPort: 8990
