apiVersion: v1
kind: Service
metadata:
  name: {{ include "nsot.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "nsot.name" . }}
    helm.sh/chart: {{ include "nsot.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8990
      protocol: TCP
      name: nsot
  selector:
    app.kubernetes.io/name: {{ include "nsot.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
